### ISSUE TITLE
The purpose of Pulsar

### ISSUE THREAD

**Issue by HelloTo4x** [Timekeeper1130/Learn-Pulsar#1]
Hi, i am reading your project, why don't u use Kafka or RabbitMQ as message queue instead of Pulsar, can you tell me why you choose Pulsar, do you know the pros and cons of Pulsar, if yes, can tell me, thank u so much

**Comment by Timekeeper1130** [comment]
I'm sorry I can't tell you the pros and cons of pulsar. I'm a beginner in the field of message queuing : (
I think Kafka or RabbitMQ is also very important in the field of message queue, so I will learn more about them in the future.
But the reason why I choose pulsar at present is that my work needs to use it.

**Comment by HelloTo4x** [comment]
tk u
